### ISSUE TITLE
Highlight the running vars in the hover popup?

### ISSUE THREAD

**Issue by zbal** [Wiredcraft/pipelines#39]
Currently, we only know when the pipeline got run, and whether it was success/failure. There is no way other than checking in the logs what were the supplied parameters.

Can we add this information in the hover box? at least that will help when a task is used as a multi purpose task.

<img width="331" alt="screen shot 2016-11-21 at 09 39 56" src="https://cloud.githubusercontent.com/assets/631984/20468155/83182bb4-afce-11e6-8543-a0e323c79e27.png">

(e.g. adding the following would be useful:

```
vars:
  - var1: abcd
  - var2: efgh
  - var3: toto (prompted)
```
)
