### ISSUE TITLE
Add checkbox type for prompt

### ISSUE THREAD

**Issue by xuqingfeng** [Wiredcraft/pipelines#73]
```yaml
prompt:
  trigger_next_step:
    type: checkbox
    default: true

...

  - name: Build image
    type: bash
    cmd: |
      ...
      {% if trigger_next_step %}
        echo "Trigger deployment"
        curl -X POST -d '{...}' -H 'Content-Type: application/json' \
          https://pipelines.com/api/webhook/<uuid>
      {% endif %}
```

**Comment by JuhaS** [comment]
Done, default for a checkbox is unchecked (false):
![image](https://user-images.githubusercontent.com/919180/29726541-b200deb2-8a02-11e7-8f17-8d643f0c7b37.png)

Example:
```yaml
prompt:
 testing:
   type: checkbox
   default: true
```
